name: Byzbl Update Game Data and Recompile wasm

on:
    workflow_dispatch:
    push:
        tags:
            - '*'
        #paths-ignore:
         #   - 'data/**'
          #  - 'build_js/**'


jobs:
    recompile-ems:
        runs-on: ubuntu-latest
        if: ${{ !cancelled() }}
        steps:
            - uses: mymindstorm/setup-emsdk@v13
              with:
                  version: 3.1.47
            - name: version
              run: emcc --version
            - uses: actions/checkout@v2
            - run: git pull
            - run: sed -zi 's/\n//g' data/data.min.json
            - run: sed -zi 's/  //g' data/data.min.json
            - name: Recompile
              run: |
                  cd build_js
                  emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
                  emmake make
            - name: Commit files
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add build_js
                  git commit -m "Recompile Emscripten"
            - name: Remove CmakeFiles
              run: |
                  rm -rf build_js/CMakeFiles
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}


